id: I9D645E3C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T20:56:30+00:00'
last_modified: '2022-06-08T03:09:08.574342+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN6858
  title: ཚལ་གུང་ཐང་གཙུག་ལག་ཁང་གི་དཀར་ཆག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    8EE2:
      image_group_id: I3CN6860
      title: ''
      total_pages: 438
      order: 1
      base_file: 8EE2.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
